version: 0.0
os: linux

env:
  variables:
    - database_password: "$database_password"
    - database_user: "$database_user"
    - emailSender_address: "$emailSender_address"
    - emailSender_password: "$emailSender_password"
    - token_secret: "$token_secret"
    - finnhub_token: "$finnhub_token"
    - client_domain: "$client_domain"

files:
  - source: /
    destination: /home/ubuntu/server

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: server_clear.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: fix_privileges.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: stop_service.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: start_service.sh
      timeout: 300
      runas: ubuntu