version: 0.2

env:
  secrets-manager:
    database_password: prod/bullshorn:database_password
    database_user: prod/bullshorn:database_user
    emailSender_address: prod/bullshorn:emailSender_address
    emailSender_password: prod/bullshorn:emailSender_password
    token_secret: prod/bullshorn:token_secret
    finnhub_token: prod/bullshorn:finnhub_token
    client_domain: prod/bullshorn:client_domain

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - scripts/*
    - target/bullshorn-0.0.1-SNAPSHOT.jar
  discard-paths: yes