server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    host: ec2-44-206-197-71.compute-1.amazonaws.com
    port: 5432
    password: ${database.password}
    username: ${database.user}
    databaseName: d5hkdocf0mm7oj
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.databaseName}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.office365.com
    port: 587
    username: ${emailSender.address}
    password: ${emailSender.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
    test-connection: false

jwt:
  secret: ${token.secret}
  expiration: 900000
finnhub:
  token:  ${finnhub.token}
client:
  url: ${client.domain}